version: 0.0
os: linux
files:
  - source: dist
    destination: /usr/share/nginx/html
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
  AfterInstall:
    - location: scripts/start.sh
      timeout: 30
  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
